### ISSUE TITLE
Tag basics - one large page or (currently) section of pages?

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern-documentation#15]
Combine or leave as separate pages? Possibly might be more tag basics docs so probably will leave as multiple pages. Will think about it.

**Comment by wion** [comment]
A couple of the pages are already kind of long-ish, so I'd leave them separate for now.  But I'm sure the content could be written a bit more concisely, so they could always be combined later. 

Another thought... for example the "Creating Lists with Conditional Tags" page, which is long, but also the topics (front-end navigation aides) would be a lot easier to understand with working demos of the examples described. So within those descriptions they could point to a spot in the Txp demo site where such examples could be seen. Having those links/demo would make it possible to write simpler descriptions, thus the overall doc page would be short.

**Comment by philwareham** [comment]
OK.

I'll continue formatting the current wiki export into manageable sections and formatting for now. The content improvement can be done in tandem with that. It'll be easier once the maze of pages are into a coherent structure.

**Comment by wion** [comment]
Agreed. I'm going to try approaching it from the top index page first.

**Comment by philwareham** [comment]
You might want to put a proposed structure diagram together first, something like:

- docs home
  - installation
    - Basic installation
    - Advanced installation
- configuration
- tag basics
- tag reference
- etc...

**Comment by wion** [comment]
Yeah, that was evident. It's going to shift and emerge gradually as the dirty laundry is separated.

Regarding the tag folders, how about this rather than two at root-level:

* tags
** tag-basics
** article.textile
** article-custom.textile
** etc
** index.textile
** etc

**Comment by philwareham** [comment]
OK that would work. Leave the tag directory in my hands - everything else is open season!
